import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from "react-router-dom";
import { ChevronsUpDown, Scan, UserRound } from "lucide-react";
import { PRIMARY_NAV, WORKSPACE_NAV } from "./navigation";
import { cn } from "@/lib/utils";
function NavItem({ item, onNavigate }) {
    const Icon = item.icon;
    return (_jsxs(NavLink, { to: item.to, end: item.exact ?? false, onClick: onNavigate, className: ({ isActive }) => cn("group flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground", isActive && "bg-sidebar-accent text-sidebar-accent-foreground"), children: [_jsx(Icon, { className: "size-4 shrink-0", strokeWidth: 1.9 }), _jsx("span", { className: "truncate", children: item.label })] }));
}
/** Sidebar content, shared by the fixed desktop rail and the mobile drawer. */
export function SidebarNav({ user, workspaceName, onNavigate }) {
    return (_jsxs("div", { className: "flex h-full flex-col bg-sidebar", children: [_jsxs("div", { className: "flex items-center gap-3 border-b border-sidebar-border px-5 py-4", children: [_jsx("div", { className: "flex size-9 shrink-0 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground", children: _jsx(Scan, { className: "size-[18px]", strokeWidth: 2 }) }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-sm font-semibold text-sidebar-foreground", children: "DueLens AI" }), _jsx("p", { className: "truncate text-xs text-muted-foreground", children: "Due Diligence Copilot" })] })] }), _jsxs("nav", { className: "flex-1 overflow-y-auto px-3 py-4", children: [_jsx("p", { className: "px-2.5 pb-2 text-[11px] font-medium tracking-wider text-muted-foreground uppercase", children: "Analysis" }), _jsx("div", { className: "space-y-0.5", children: PRIMARY_NAV.map((item) => (_jsx(NavItem, { item: item, onNavigate: onNavigate }, item.to))) }), _jsx("p", { className: "mt-6 px-2.5 pb-2 text-[11px] font-medium tracking-wider text-muted-foreground uppercase", children: "Workspace" }), _jsxs("div", { className: "space-y-0.5", children: [_jsxs("div", { className: "flex items-center gap-2.5 rounded-md border border-sidebar-border px-2.5 py-2", children: [_jsx("span", { className: "size-1.5 shrink-0 rounded-full bg-risk-low", "aria-hidden": true }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-sm font-medium text-sidebar-foreground", children: workspaceName ?? "Workspace" }), _jsx("p", { className: "truncate text-xs text-muted-foreground", children: "Active workspace" })] })] }), WORKSPACE_NAV.map((item) => (_jsx(NavItem, { item: item, onNavigate: onNavigate }, item.to)))] })] }), _jsx("div", { className: "border-t border-sidebar-border p-3", children: _jsxs("button", { type: "button", className: "grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2.5 rounded-md px-2 py-2 text-left transition-colors hover:bg-sidebar-accent", children: [_jsx("span", { className: "flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground", children: user?.initials ? (_jsx("span", { className: "text-xs font-semibold", children: user.initials })) : (_jsx(UserRound, { className: "size-4", strokeWidth: 1.9 })) }), _jsxs("span", { className: "min-w-0", children: [_jsx("span", { className: "block truncate text-sm font-medium text-sidebar-foreground", children: user?.name ?? "User" }), _jsx("span", { className: "block truncate text-xs text-muted-foreground", children: user?.role ?? "Signed out" })] }), _jsx(ChevronsUpDown, { className: cn("size-4 shrink-0 text-muted-foreground"), strokeWidth: 1.9 })] }) })] }));
}
